scrape_configs:
  - job_name: "sample_monitoring-auth"
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:9000"]
  - job_name: "sample_monitoring-pn"
    scrape_interval: 5s
    metrics_path: "/pn/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8081"]
