#!/bin/bash
NAMES=$(cztlist)
NAMES_ARRAY=($NAMES)

RED='\033[0;31m'
GR='\033[0;32m'
PR='\033[0;36m'
YL='\033[0;33m'
NC='\033[0m' # No Color

color=$YL
RESULT=""

for i in ${NAMES_ARRAY[@]}; do
   status=$(systemctl is-active $i)
   if [ "$status" == "active" ]; then
      color=$GR
   elif [ "$status" == "inactive" ]; then
      color=$RED
   fi
   RESULT="$RESULT ${PR}$i${NC} status ${color}$status${NC}\n"
done

printf "$RESULT" | column -t 
