version: "3.7"

services:
  grafana:
    build: "./config/grafana"
    ports:
      - 3000:3000
    #volumes:
    #  - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    configs:
      - source: prometheusCfg
        target: /etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      monitoring:
        aliases:
          - prometheus
networks:
  monitoring:

configs:
  prometheusCfg:
    file: ./config/prometheus.yml
