version: '3.4'

services:
  console:
    image: docker.redpanda.com/redpandadata/console:latest
    ports:
      - 8095:8080
    environment:
      KAFKA_BROKERS: kafka:19092
    container_name: kafka-console
    networks:
      - czt-network    

  zoo:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo
    container_name: zoo
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo:2888:3888
    networks:
      - czt-network    

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo
    networks:
      - czt-network    

  auth:
    image: deadjack/czt-auth:latest
#    image: nexus.ocrv.com.rzd/czt-portal/auth:ocrv
    ports:
      - "9000:9000"
    depends_on:
      - auth-db
    environment:
      - JAVA_ARGS=
        --spring.datasource.url=jdbc:postgresql://auth-db:5432/authdb?rewriteBatchedStatements=true
        --spring.datasource.username=auth
        --spring.datasource.password=auth-secret
        --client.pkce=false
        --token.duration.access=3
        --token.duration.refresh=30
        --token.duration.code=10
    networks:
      - czt-network    
  auth-db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=authdb
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=auth-secret
    restart: on-failure
    networks:
      - czt-network
  fs-db:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=fsdb
      - POSTGRES_USER=fs_service
      - POSTGRES_PASSWORD=fs-secret
    restart: on-failure
    volumes:
      - "./volumes/fs-db/pgdata/data:/var/lib/postgresql/data"    
    networks:
      - czt-network    
  pn-db:
    image: postgres:14
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=pndb
      - POSTGRES_USER=pn_service
      - POSTGRES_PASSWORD=pn-secret
    restart: on-failure
    volumes:
      - "./volumes/pn-db/pgdata/data:/var/lib/postgresql/data"
    networks:
      - czt-network    
  bff:
    depends_on:
      - auth
    image: deadjack/czt-bff:latest
    ports:
      - "9002:9002"
    environment:
      - JAVA_ARGS=
        --bff.serviceDefinitions.oauth2.domain=auth
        --bff.serviceDefinitions.oauth2.port=9000
        --bff.serviceDefinitions.oauth2.prefix=/oauth2
        --bff.serviceDefinitions.fs.domain=fs
        --bff.serviceDefinitions.fs.port=8080
        --bff.serviceDefinitions.fs.prefix=/fs
        --bff.serviceDefinitions.pn.domain=pn
        --bff.serviceDefinitions.pn.port=8081
        --bff.serviceDefinitions.pn.prefix=/pn
        --bff.serviceDefinitions.portal.domain=auth
        --bff.serviceDefinitions.portal.port=9000
        --bff.serviceDefinitions.portal.prefix=/portal
        --spring.datasource.url=jdbc:postgresql://auth-db:5432/authdb?rewriteBatchedStatements=true
        --spring.datasource.username=auth
        --spring.datasource.password=auth-secret
    networks:
      - czt-network    
  fs:
    depends_on:
      - fs-db
      - auth-db
      - bff
    image: deadjack/czt-fs-backend:latest
    ports:
      - "8080:8080"
    environment:
      - JAVA_ARGS=
        --com.ocrv.auth.issuerUri=http://auth:9000
        --com.ocrv.fs.rover.datasources.fs.url=jdbc:postgresql://fs-db:5432/fsdb?rewriteBatchedStatements=true
        --com.ocrv.fs.rover.datasources.fs.username=fs_service
        --com.ocrv.fs.rover.datasources.fs.password=fs-secret
        --com.ocrv.fs.rover.datasources.pn.url=jdbc:postgresql://pn-db:5432/pndb?rewriteBatchedStatements=true
        --com.ocrv.fs.rover.datasources.pn.username=pn_service
        --com.ocrv.fs.rover.datasources.pn.password=pn-secret
        --com.ocrv.fs.rover.datasources.auth.url=jdbc:postgresql://auth-db:5432/authdb?rewriteBatchedStatements=true
        --com.ocrv.fs.rover.datasources.auth.username=auth
        --com.ocrv.fs.rover.datasources.auth.password=auth-secret
        --spring.datasource.jdbc-url=jdbc:postgresql://fs-db:5432/fsdb?rewriteBatchedStatements=true
        --spring.datasource.url=jdbc:postgresql://fs-db:5432/fsdb?rewriteBatchedStatements=true
        --spring.datasource.username=fs_service
        --spring.datasource.password=fs-secret
        --spring.auth.datasource.jdbc-url=jdbc:postgresql://auth-db:5432/authdb?rewriteBatchedStatements=true
        --spring.auth.datasource.url=jdbc:postgresql://auth-db:5432/authdb?rewriteBatchedStatements=true
        --spring.auth.datasource.username=auth
        --spring.auth.datasource.password=auth-secret
        --springdoc.api-docs.enabled=true
    networks:
      - czt-network  
  pn:
    depends_on:
      - pn-db
      - bff
    #image: deadjack/czt-pn-backend:latest
    image: pn-back:test
    ports:
      - "8081:8081"
    environment:
      - JAVA_ARGS=
        --com.ocrv.auth.issuerUri=http://auth:9000
        --spring.datasource.url=jdbc:postgresql://pn-db:5432/pndb?rewriteBatchedStatements=true
        --spring.datasource.username=pn_service
        --spring.datasource.password=pn-secret
        --springdoc.api-docs.enabled=true
    networks:
      - czt-network      
networks:
  czt-network:
    driver: bridge        
