server:
  port: 8080
  base-url: /
  assets-path: /app/assets

branding:
  hide-footer: true
  custom-footer: |
    <p>OCRV</p>
  logo-url: /assets/ocrv.png
  favicon-url: /assets/figure.png

theme:
  background-color: 225 14 15
  primary-color: 157 47 65
  contrast-multiplier: 1.1

#theme:
#  background-color: 229 19 23
#  contrast-multiplier: 1.2
#  primary-color: 222 74 74
#  positive-color: 96 44 68
#  negative-color: 359 68 71

pages:
  - name: irk.czt
    columns:
      - size: small
        widgets:
          - type: clock
            hour-format: 24h
            timezones:
              - timezone: Asia/Irkutsk
                label: IRK
              - timezone: Europe/Moscow
                label: MSK

      - size: full
        widgets:
          - type: bookmarks
            style: horizontal-cards-2
            groups:
              - title: Swagger
                color: 200 50 50
                links:
                  - title: Auth
                    url: https://auth.irk.czt.ocrv.com.rzd/swagger-ui/index.html
                    icon: si:swagger

                  - title: PN
                    url: https://resource.irk.czt.ocrv.com.rzd/pn/swagger-ui/index.html
                    icon: si:swagger

                  - title: FS
                    url: https://resource.irk.czt.ocrv.com.rzd/fs/swagger-ui/index.html
                    icon: si:swagger

                  - title: Gateway
                    url: https://resource.irk.czt.ocrv.com.rzd/gateway/swagger-ui/index.html
                    icon: si:swagger

              - title: Dev Utils
                color: 10 70 50
                links:
                  - title: Kafka
                    url: https://kafka.irk.czt.ocrv.com.rzd
                    icon: si:apachekafka

                  - title: DBeaver | cbadmin:RES517fghj
                    url: https://db.irk.czt.ocrv.com.rzd
                    icon: si:dbeaver

                  - title: Metrics | owpk:1422
                    url: https://metrics.irk.czt.ocrv.com.rzd
                    icon: si:grafana

                  - title: Portainer | owpk:1422
                    url: https://portainer.irk.czt.ocrv.com.rzd
                    icon: si:portainer

              - links:
                  - title: OCRV mine
                    icon: si:ruby
                    url: https://main.ocrv.ru

          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: Auth | server:9000 debug:5000
                url: http://auth.irk.czt.ocrv.com.rzd/actuator
                icon: si:swagger

              - title: PN | server:8090 debug:5003
                url: http://resource.irk.czt.ocrv.com.rzd/pn/actuator
                icon: si:swagger

              - title: FS | server:8091 debug:5004
                url: http://resource.irk.czt.ocrv.com.rzd/fs/actuator
                icon: si:swagger

              - title: Gateway | server:8082 debug:5005
                url: http://resource.irk.czt.ocrv.com.rzd/gateway/actuator
                icon: si:swagger

  - name: czt resources
    columns:
      - size: full
        widgets:
          - type: bookmarks
            style: horizontal-cards-2
            groups:
              - title: DEV OCRV
                color: 100 50 50
                links:
                  - title: cztp-dev-lb01
                    url: 172.22.10.150
                    icon: si:nginx

                  - title: cztp-dev-lb02
                    url: 172.22.10.156
                    icon: si:nginx

                  - title: cztp-dev-app01
                    url: 172.22.10.253
                    icon: si:spring

                  - title: cztp-dev-app02
                    url: 172.22.10.254
                    icon: si:spring

                  - title: cztp-dev-app03
                    url: 172.22.10.133
                    icon: si:spring

                  - title: cztp-dev-db01
                    url: 172.22.10.101
                    icon: si:postgresql

                  - title: cztp-dev-db02
                    url: 172.22.10.110
                    icon: si:postgresql

              - title: TEST OCRV
                color: 100 50 50
                links:
                  - title: cztp-dev-lb01
                    url: 172.22.194.102
                    icon: si:nginx

                  - title: cztp-test-app01
                    url: 172.22.194.100
                    icon: si:spring

                  - title: cztp-test-app02
                    url: 172.22.194.131
                    icon: si:spring

                  - title: cztp-test-app03
                    url: 172.22.194.146
                    icon: si:spring

                  - title: cztp-test-db01
                    url: 172.22.194.103
                    icon: si:postgresql

              - title: STABLE OCRV
                color: 100 50 50
                links:
                  - title: cztp-stable-lb01
                    url: 172.22.194.178
                    icon: si:nginx
                  - title: cztp-stable-app01
                    url: 172.22.194.163
                    icon: si:spring
                  - title: cztp-stable-app02
                    url: 172.22.194.170
                    icon: si:spring
                  - title: cztp-stable-app03
                    url: 172.22.194.168
                    icon: si:spring
                  - title: cztp-stable-db01
                    url: 172.22.194.150
                    icon: si:postgresql

              - title: UTILS
                color: 200 50 50
                links:
                  - title: GRAFANA (dev) | viewer 1qaz2wsx
                    url: https://grafana.czt.dev.ocrv.com.rzd/
                    icon: si:grafana
                  - title: PORTAINER | viewer 1qaz2wsx
                    url: http://portainer.czt.dev.ocrv.com.rzd/
                    icon: si:portainer

  - name: czt.stable
    columns:
      - size: small
        widgets:
          - type: clock
            hour-format: 24h
            timezones:
              - timezone: Asia/Irkutsk
                label: IRK
              - timezone: Europe/Moscow
                label: MSK

      - size: full
        widgets:
          - type: bookmarks
            style: horizontal-cards-2
            groups:
              - title: Front End app
                color: 200 50 50
                links:
                  - title: PN front
                    url: https://pn.czt.stable.ocrv.com.rzd
                    icon: si:react

                  - title: FA front
                    url: https://fs.czt.stable.ocrv.com.rzd
                    icon: si:react
              - title: Swagger
                color: 200 50 50
                links:
                  - title: Auth
                    url: https://auth.czt.stable.ocrv.com.rzd/swagger-ui/index.html
                    icon: si:swagger

                  - title: PN
                    url: https://resource.czt.stable.ocrv.com.rzd/pn/swagger-ui/index.html
                    icon: si:swagger

                  - title: FS
                    url: https://resource.czt.stable.ocrv.com.rzd/fs/swagger-ui/index.html
                    icon: si:swagger

                  - title: Gateway
                    url: https://resource.czt.stable.ocrv.com.rzd/gateway/swagger-ui/index.html
                    icon: si:swagger

          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: Auth | server:9000 debug:5000
                url: https://auth.czt.stable.ocrv.com.rzd/actuator
                icon: si:swagger

              - title: PN | server:8090 debug:5003
                url: https://resource.czt.stable.ocrv.com.rzd/pn/actuator
                icon: si:swagger

              - title: FS | server:8091 debug:5004
                url: https://resource.czt.stable.ocrv.com.rzd/fs/actuator
                icon: si:swagger

              - title: Gateway | server:8082 debug:5005
                url: https://resource.czt.stable.ocrv.com.rzd/gateway/actuator
                icon: si:swagger
